'use strict'
const fs = require('node:fs')
const vm = require('node:vm')
const path = require('node:path')
const assert = require('node:assert/strict')
const memory = new Map()
global.localStorage = { getItem: (k) => memory.get(k) || null, setItem: (k, v) => memory.set(k, String(v)), removeItem: (k) => memory.delete(k) }
global.window = { location: { hostname: 'localhost' } }
for (const file of ['config', 'auth-demo', 'media-review']) vm.runInThisContext(fs.readFileSync(path.join(__dirname, '../assets/js', `${file}.js`), 'utf8'))
const auth = window.RVCourseStore
const media = window.RVMediaReview
const adminLogin = () => auth.adminLogin('admin@rvfisiologia.test', 'rv30admin')
assert.equal(auth.supportCreate('Assunto', 'Oi').ok, false)
adminLogin()
auth.adminCreateStudent({ name: 'Aluno Um', email: 'um@test.local', password: 'SenhaTeste1' }, 'rv30')
auth.adminCreateStudent({ name: 'Aluno Dois', email: 'dois@test.local', password: 'SenhaTeste2' }, 'rv30')
auth.adminLogout()
auth.login('um@test.local', 'SenhaTeste1')
assert.equal(auth.supportCreate('Assunto', 'Sem curso', 'forca').ok, false)
assert.equal(auth.supportCreate('a', 'teste').ok, false)
assert.equal(auth.supportCreate('Assunto', 'x'.repeat(2001)).ok, false)
const thread = auth.supportCreate('Duvida de acesso', '<script>alert(1)</script>', 'rv30').threadId
assert(thread)
assert.equal(auth.supportThreads()[0].messages[0].body, '<script>alert(1)</script>')
auth.logout()
auth.login('dois@test.local', 'SenhaTeste2')
assert.equal(auth.supportThreads().length, 0)
assert.equal(auth.supportThreads(true).length, 0)
assert.equal(auth.supportSend(thread, 'invasao').ok, false)
assert.equal(auth.supportRead(thread).ok, false)
assert.equal(auth.supportResolve(thread).ok, false)
assert.equal(auth.supportSend(thread, 'falso admin', true).ok, false)
adminLogin()
assert.equal(auth.supportThreads(true)[0].unread, 1)
assert.equal(auth.supportRead(thread, true).ok, true)
assert.equal(auth.supportThreads(true)[0].unread, 0)
assert.equal(auth.supportSend(thread, 'Resposta da equipe', true).ok, true)
assert.equal(auth.supportResolve(thread).ok, true)
auth.adminLogout()
auth.logout()
auth.login('um@test.local', 'SenhaTeste1')
assert.equal(auth.supportThreads()[0].messages[1].body, 'Resposta da equipe')
assert.equal(auth.supportThreads()[0].unread, 1)
assert.equal(auth.supportThreads()[0].status, 'resolved')
auth.supportSend(thread, 'Reabrir')
assert.equal(auth.supportThreads()[0].status, 'open')
const session = JSON.parse(localStorage.getItem(auth.storage.session))
session.expiresAt = 'not-a-date'
localStorage.setItem(auth.storage.session, JSON.stringify(session))
assert.equal(auth.supportThreads().length, 0)
assert.equal(auth.supportSend(thread, 'expirado').ok, false)
assert.equal(auth.account(), null)
assert.equal(auth.setDayComplete('rv30', 1, true).ok, false)

assert.equal(media.import('rv30', [{ name: 'video aula 00.mp4' }]).ok, false)
adminLogin()
assert.equal(media.import('rv30', [{ name: 'video aula 31.mp4' }]).ok, false)
assert.equal(media.import('rv30', [{ name: 'video aula 01.mp4' }, { name: 'aula 01.mov' }]).ok, false)
assert.equal(media.driveFileId('https://drive.google.com.evil.test/file/d/id/view'), null)
assert.equal(media.driveFileId('javascript:alert(1)'), null)
assert.equal(media.driveFileId('https://evil@drive.google.com/file/d/id/view'), null)
assert.equal(media.approveBatch('rv30').ok, false)
assert.equal(media.import('rv30', [{ name: 'video aula 00.mp4' }]).ok, true)
assert.equal(media.update('rv30', 0, { approved: true }).ok, false)
const files = Array.from({ length: 31 }, (_, day) => ({ name: `video aula ${String(day).padStart(2, '0')}.mp4`, driveUrl: `https://drive.google.com/file/d/test_${day}/view` })).reverse()
assert.equal(media.import('rv30', files).ok, true)
assert.equal(media.list('rv30')[0].day, 0)
assert.equal(media.manifest('rv30').status, 'draft')
for (let day = 0; day <= 30; day++) assert.equal(media.update('rv30', day, { approved: true }).ok, true)
assert.equal(media.approveBatch('rv30').ok, true)
assert.equal(media.manifest('rv30').status, 'approved_for_ingestion')
assert.equal(media.manifest('rv30').published, false)
assert.equal(media.import('rv30', [files[0]]).ok, true)
assert.equal(media.manifest('rv30').status, 'draft')
assert.equal(media.list('rv30').find((i) => i.day === 30).approved, false)
assert.equal(media.approveBatch('rv30').ok, false)
window.RV_COURSE_CONFIG.testMode = false
assert.equal(auth.supportThreads(true).length, 0)
assert.equal(media.list('rv30').length, 0)
assert.equal(media.manifest('rv30'), null)
assert.equal(media.approveBatch('rv30').ok, false)
for (const hostname of ['projeto.rvfisiologista.com.br', 'staging.pages.dev', 'localhost.evil.test']) {
  window.location.hostname = hostname
  vm.runInThisContext(fs.readFileSync(path.join(__dirname, '../assets/js/config.js'), 'utf8'))
  assert.equal(window.RV_COURSE_CONFIG.testMode, false)
  assert.equal(window.RV_COURSE_CONFIG.enablePaymentSimulation, false)
}
console.log('OK: suporte isolado, mensagens persistentes, RBAC, expiracao, videos ordenados, revisao obrigatoria e demo bloqueada fora do loopback.')
